apple/swift-nio-imap

- CONTRIBUTING.md
- dev/git.commit.template
Update `CONTRIBUTING.md` to use the standard SwiftNIO document.
This matches the rest of the SwiftNIO project.
* Update `CONTRIBUTING.md`
* Add `dev/git.commit.template` (referenced from `CONTRIBUTING.md`)
> Adopt SwiftNIO CONTRIBUTING.md

- Sources/NIOIMAPCore/CommandEncodeBuffer.swift
- Sources/NIOIMAPCore/EncodeBuffer.swift
- Sources/NIOIMAPCore/Grammar/Command/Command.swift
- Sources/NIOIMAPCore/Grammar/Command/CommandStreamPart.swift
- Sources/NIOIMAPCore/Grammar/Command/TaggedCommand.swift
- Sources/NIOIMAPCore/Grammar/FetchAttribute.swift
- Sources/NIOIMAPCore/Grammar/Message/MessageAttributes.swift
- Sources/NIOIMAPCore/Grammar/Response/Response.swift
- Sources/NIOIMAPCore/Grammar/Response/ResponseText.swift
- Sources/NIOIMAPCore/Grammar/Response/ResponseTextCode.swift
- Sources/NIOIMAPCore/Grammar/SectionSpec.swift
- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifier.swift
- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierRange.swift
- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierSet.swift
- Sources/NIOIMAPCore/ResponseEncodeBuffer.swift
- Tests/NIOIMAPCoreTests/Grammar/FetchAttributeTests.swift
- Tests/NIOIMAPCoreTests/Grammar/Message/MessageAtributesTests.swift
- Tests/NIOIMAPCoreTests/Grammar/Response/Response+Tests.swift
With this PR the implementation of `CustomDebugStringConvertible` generally uses new `makeDescription` convenience methods on the three encode buffers, e.g.:
```swift
extension ResponseEncodeBuffer {
static func makeDescription(_ closure: (inout ResponseEncodeBuffer) -> Void) -> String
}
```
such that conformance can be implemented as e.g.
```swift
extension Command: CustomDebugStringConvertible {
public var debugDescription: String {
CommandEncodeBuffer.makeDescription {
$0.writeCommand(self)
}
}
}
```
This also adds `CustomDebugStringConvertible` to `MessageAttribute` and `StreamingKind`.
> Cleanup CustomDebugStringConvertible conformance

- Sources/NIOIMAPCore/Grammar/Body/Body.swift
- Tests/NIOIMAPCoreTests/Grammar/Body/BodyStructure+Tests.swift
This fixes a few shortcomings of `BodyStructure`’s `RandomAccessCollection` conformance:
`index(before:)` and `index(after:)` now work properly, and there are better tests for these, too.
`startIndex` now starts at the “empty” `SectionSpecifier.Part` i.e. the complete part / structure.
Can iterate into `message/rfc822` sub-parts.
Added a failing
```swift
public func find(_ position: SectionSpecifier.Part) -> BodyStructure?
```
to look up a part — and return `nil` if it’s not found / not valid.
> Fix BodyStructure’s RandomAccessCollection conformance

- Sources/NIOIMAPCore/Grammar/Body/Body.swift
- Sources/NIOIMAPCore/Grammar/SectionSpec.swift
- Tests/NIOIMAPCoreTests/Grammar/Body/BodyStructure+Tests.swift
- Tests/NIOIMAPCoreTests/Grammar/Section/SectionSpecTests.swift
Add convenience methods to `BodyStructure` and `SectionSpecifier.Part`.
Simplifies some common operations on `BodyStructure` and `SectionSpecifier.Part`.
Adds these convenience methods:
```swift
extension BodyStructure {
public func enumerateParts(_ closure: (SectionSpecifier.Part, BodyStructure) throws -> Void) rethrows
}
```
```swift
extension SectionSpecifier.Part {
public func dropFirst()
public func dropLast() -> SectionSpecifier.Part
public func appending(_ element: Int) -> SectionSpecifier.Part
public func isSubPart(of other: SectionSpecifier.Part) -> Bool
}
```
> More BodyStructure / SectionSpec convenience

- Sources/NIOIMAP/Client/IdleStateMachine.swift
- Tests/NIOIMAPTests/Client/IdleStateMachineTests.swift
Need to allow Response.fetch while in IDLE.
While we’re in the `IDLE` state, we need to allow untagged responses. In addition to `Response.untagged`, we need to also allow `Response.fetch` since those are also _untagged_. The `FETCH` related were split out to allow streaming.
Fixed the `switch` inside `func receiveResponse_idlingState()`.
Added a test case.
Fixes #716
> Need to allow Response.fetch while in IDLE.

- Sources/NIOIMAPCore/Grammar/Message/MessageAttributes.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Message.swift
- Tests/NIOIMAPCoreTests/Grammar/Message/MessageAtributesTests.swift
- Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Message+Tests.swift
- Tests/NIOIMAPCoreTests/ResponseStreamingTests.swift
This is (already) being handled by `FetchResponse.streamingBegin` / `StreamingKind`.
The `MessageAttribute.binary` case was a left-over from before `.streamingBegin` was added.
> Remove MessageAttribute.binary

- Sources/NIOIMAPCore/Grammar/Message/MessageAttributes.swift
- Sources/NIOIMAPCore/Grammar/Response/Response.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Fetch.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Message.swift
- Sources/NIOIMAPCore/ResponseEncodeBuffer.swift
- Tests/NIOIMAPCoreTests/Grammar/Response/Response+Tests.swift
- Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Message+Tests.swift
- Tests/NIOIMAPCoreTests/ResponseStreamingTests.swift
Allow `NIL` response for a particular body section
The [RFC 3501 section 7.4.2][3501FetchResponse] `FETCH` response for a `BODY[<section>]<<origin octet>>` (or the corresponding `BINARY` from [RFC 3516][3516]) is allowed to be `NIL` (it’s an `nstring`), corresponding to a non-existing body section.
For example, if the client requests `BODY.PEEK[4.2]` and there’s no 4.2 for that particular message, the server will respond with `BODY[4.2] NIL`.
Add a `MessageAttribute` corresponding to this `NIL` value.
Note that the non-nil version uses `FetchResponse.streamingBegin(…)`, `.streamingBytes(…)`, and `.streamingEnd`, whereas the `NIL` variant uses `FetchResponse.simpleAttribute` since it won’t be streaming any data.
Added test cases for encoding and parsing.
[3501FetchResponse]: …
> Allow NIL response for a particular body section

- Sources/NIOIMAPCore/Parser/ParserLibrary.swift
- Tests/NIOIMAPCoreTests/Grammar/EncodeTestClass.swift
- Tests/NIOIMAPCoreTests/Parser/IMAPParserTests.swift
- Tests/NIOIMAPCoreTests/Parser/SynchronizingLiteralParserTests.swift
- Tests/NIOIMAPCoreTests/TestUtilities.swift
- Tests/NIOIMAPTests/TestUtilities.swift
Motivation:
#fileID introduced in Swift 5.3, so no longer need to use #file anywhere                                  
Modifications:
Changed #file to #filePath or #fileID depending on situation
> Use #fileID/#filePath instead of #file

- Sources/NIOIMAPCore/Grammar/Command/Command.swift
- Sources/NIOIMAPCore/Grammar/Search/SearchKey.swift
- Tests/NIOIMAPCoreTests/Parser/RoundtripTests.swift
- Tests/NIOIMAPTests/CommandEncoder+Tests.swift
We’d previously always output the `CHARSET UTF-8` for search commands, even when the search didn’t include any text. With this e.g.
```
C: U59 UID SEARCH RETURN (MIN ALL) CHARSET UTF-8 UID 1:*
```
becomes
```
C: U59 UID SEARCH RETURN (MIN ALL) UID 1:*
```
> Only include CHARSET in SEARCH command when there’s text

- Sources/NIOIMAPCore/EncodeBuffer.swift
- Sources/NIOIMAPCore/Grammar/Response/Response.swift
- Sources/NIOIMAPCore/ResponseEncodeBuffer.swift
- Tests/NIOIMAPCoreTests/Grammar/Response/Response+Tests.swift
Ability to create decription from `Response`
This allows creating a (debug) `String` from a `Response` — either with or without PII (personally identifiable information).
> Ability to create decription from Response

- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierSet.swift
- Tests/NIOIMAPCoreTests/Grammar/UID/UIDSetTests.swift
Call through to `RangeSet` for `MessageIdentifierSet`’s `SetAlgebra` conformance where possible
`MessageIdentifierSet` conforms to `SetAlgebra`, but some methods were relying on the default protocol implementations instead of using the underlying `RangeSet`’s implementation. This could lead to poor performance.
> Call through to RangeSet for MessageIdentifierSet’s SetAlgebra conformance where possible

- Sources/NIOIMAPCore/Grammar/Response/ExtendedSearchResponse.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser.swift
- Tests/NIOIMAPCoreTests/Grammar/Mailbox/MailboxData+Tests.swift
- Tests/NIOIMAPCoreTests/Grammar/Response/ESearchResponse+Tests.swift
- Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Mailbox+Tests.swift
- Tests/NIOIMAPCoreTests/Parser/IMAPParserTests.swift
Change
```swift
public var uid: Bool
```
to
```swift
public var kind: Kind
public enum Kind: Hashable {
case sequenceNumber
case uid
}
```
> Use enum for `ExtendedSearchResponse` UID vs. sequence number

- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierRange.swift
- Tests/NIOIMAPCoreTests/Grammar/UID/UIDRangeTests.swift
Add `MessageIdentifierRange` convenience
```swift
public var isEmpty: Bool
public func clamped(to limits: MessageIdentifierRange) -> MessageIdentifierRange
public func overlaps(_ other: MessageIdentifierRange) -> Bool
public func contains(_ element: IdentifierType) -> Bool
```
> Add MessageIdentifierRange convenience

- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Date.swift
- Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Message+Tests.swift
Parse `INTERNALDATE`s like this one where the single digit day has neither a leading space nor a `0`:
```
8-Mar-2023 12:16:47 +0800
```
The RFC specifies that a single digit day should have a leading space. But some servers don't send one.
> Parse `INTERNALDATE`s without a leading digit or space

- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Body.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser.swift
- Sources/NIOIMAPCore/Parser/ParserLibrary.swift
- Tests/NIOIMAPCoreTests/Parser/CommandParser+Tests.swift
- Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Body+Tests.swift
Allow non-ASCII values in BODYSTRUCTURE parameters
This is not allowed by RFC 3501, but some emails have non-ASCII headers, and some servers
end up copying the non-ASCII values into `BODYSTRUCTURE` parameter fields values, and
we still want to be able to be able to parse the overall `BODYSTRUCTURE`.
This adds a new `parseStringAllowingNonASCII()` which calls into a new `parseQuotedAllowingNonASCII()`.
This is then used by `parseBodyFieldParam_singlePair()` which now also uses `String(bestEffortDecodingUTF8Bytes:)` to do a best-effort decoding of non-ASCII.
We don’t do any sensible character-set decoding when seeing non-ASCII, but the goal is merely to not fail parsing, such that we can still handle these responses, i.e _graceful degradation_ when we parse these otherwise invalid …
> Allow non-ASCII values in BODYSTRUCTURE parameters

- Sources/NIOIMAPCore/Grammar/Modifier/ModificationSequenceValue.swift
- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifier.swift
- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierSet.swift
- Sources/NIOIMAPCore/Grammar/UID/UIDValidity.swift
Make generic functions that are public inlinable
Allow for optimizations of client library using these generic functions.
Added `@inlinable` (and `@usableFromInline`).
> Make generic functions that are public inlinable

- Sources/NIOIMAP/Client/AuthenticationStateMachine.swift
- Tests/NIOIMAPTests/Client/AuthenticationStateMachineTests.swift
- Tests/NIOIMAPTests/Coders/ClientStateMachineTests.swift
This fixes #729 and adds tests.
The client will hang if it receives an untagged response during authentication. Gmail does send such a response, and Gmail OAUTH is thus broken without this fix.
Thanks for @stephengoodman for tracking down this issue.
Ignore untagged responses inside `AuthenticationStateMachine`. Add tests.
Gmail authentication works.
> Fix for receiving untagged response during SASL auth

- Sources/NIOIMAPCore/Grammar/SectionSpec.swift
- Tests/NIOIMAPCoreTests/Grammar/Section/SectionSpecTests.swift
Add check if a MIME part (specifier) is a (direct) child node of another, e.g. if `2.1` is a child node of `2`.
This is a common operation when working with `SectionSpecifier.Part`.
Follows the pattern of `isSubPart(of:)`.
> Add SectionSpecifier.Part.isChildPart(of:)

- Sources/NIOIMAPCore/Grammar/ByteRange/ByteRange.swift
- Sources/NIOIMAPCore/Grammar/ByteRange/MessagePathByteRange.swift
- Sources/NIOIMAPCore/Grammar/FetchAttribute.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser.swift
- Tests/NIOIMAPCoreTests/Grammar/ByteRange/ByteRange+Tests.swift
- Tests/NIOIMAPCoreTests/Parser/IMAPParserTests.swift
This is a follow up to #736 — a few more things needed renaming.
The [IMAP Paged SEARCH & FETCH Extension ](https://datatracker.ietf.org/doc/draft-ietf-extra-imap-partial/) is also called “Partial”, and thus renaming the existing `Partial` type(s) would make it less confusing to implement that RFC.
> 2nd part of renaming Partial → ByteRange

- Sources/NIOIMAPCore/Grammar/FetchModifier.swift
- Sources/NIOIMAPCore/Grammar/Partial/PartialRange.swift
- Sources/NIOIMAPCore/Grammar/Partial/SearchReturnData+Partial.swift
- Sources/NIOIMAPCore/Grammar/Search/SearchReturnData.swift
- Sources/NIOIMAPCore/Grammar/Search/SearchReturnOption.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Fetch.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Partial.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Search.swift
- Tests/NIOIMAPCoreTests/Grammar/FetchModifier+Tests.swift
- Tests/NIOIMAPCoreTests/Grammar/Partial/PartialRange+Tests.swift
- Tests/NIOIMAPCoreTests/Grammar/Search/SearchReturnData+Tests.swift
- Tests/NIOIMAPCoreTests/Grammar/Search/SearchReturnOption+Tests.swift
- Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Fetch+Tests.swift
- Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Search+Tests.swift
- scripts/soundness.sh
IMAP Paged SEARCH & FETCH Support
This adds support for the [IMAP Paged SEARCH & FETCH Extension ](https://datatracker.ietf.org/doc/draft-ietf-extra-imap-partial/) — also called “Partial”.
This extension allows clients to limit the number of SEARCH results or FETCH results returned by the server.
Add support for encoding & parsing for
1. `PARTIAL` as part of a `SEARCH` command, e.g.
```
A02 UID SEARCH RETURN (PARTIAL 23500:24000) UNDELETED
```
2. `PARTIAL` as part of the response to a `SEARCH` command, e.g.
```
* ESEARCH (TAG "A02") UID PARTIAL (-1:-4 67,100:102)
```
3. `PARTIAL` as of a `FETCH`, e.g.
```
A101 UID FETCH 25900:26600 (UID FLAGS) (PARTIAL -1:-30 CHANGEDSINCE 98305)
```
> IMAP Paged SEARCH & FETCH Support

- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Sequence.swift
- Tests/NIOIMAPCoreTests/TestUtilities.swift
- Tests/NIOIMAPTests/TestUtilities.swift
1. Fix warnings about missing `@retroactive` (in tests).
2. Fix warnings about `generic parameter 'T' shadows generic parameter` in code.
> Fix compiler warnings for Swift 5.9

- Sources/NIOIMAPCore/Grammar/Mailbox/MailboxName.swift
Reduce `MemoryLayout<MailboxPath>.size` and `MemoryLayout<MailboxName>.size`.
Some users have a lot of mailboxes, and reducing the size of these helps.
1. `MailboxName`: Instead of storing `hashValue: Int` (8 bytes on 64 bit), store `_hashValue: UInt32` (4 bytes).
2. `MailboxPath `: Instead of storing `pathSeparator: Character?` (16 bytes on 64 bit), store `_pathSeparator: UInt8` (1 bytes).
The size of `MailboxPath` drops from 32 bytes to 13 bytes (on 64 bit).
> Reduce size of MailboxName and MailboxPath

- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Envelope.swift
- Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Envelope+Tests.swift
Fix envelope parsing for multi-address fields in IMAP
The current implementation of the envelope parsing logic fails to correctly handle multiple addresses in fields like FROM, TO, CC, and BCC. This is due to the parser not accounting for potential spaces between addresses, leading to failures when encountering envelope fields with more than one address.
- Updated the email address parsing logic to correctly handle spaces between addresses in multi-address scenarios.
- Updated unit test to cover scenarios with multiple addresses in envelope fields.
After this change, envelope fields containing multiple addresses, such as the TO, FROM, CC, and BCC fields, are correctly parsed, regardless of the spacing between addresses.
> Fix envelope multiple addresses parsing

- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser.swift
- Sources/NIOIMAPCore/Parser/ResponseParser.swift
When hitting a limit and throwing an error, include the limited and maximum value.
`ExceededLiteralSizeLimitError`,
`ExceededMaximumMessageAttributesError`, and
`ExceededMaximumBodySizeError` now include _actual_ and _maximum_ values.
This makes it easier to reason about those errors, particularly in logs.
> Include actual and limit values in errors

- Sources/NIOIMAPCore/Grammar/AttributeFlag.swift
- Sources/NIOIMAPCore/Grammar/Entry/EntryKindRequest.swift
- Sources/NIOIMAPCore/Grammar/Entry/EntryTypeResponse.swift
- Sources/NIOIMAPCore/Grammar/InitialResponse.swift
- Sources/NIOIMAPCore/Grammar/Media/Media.swift
Use `let` for static constants, which shouldn't be mutable.
These will be errors with Swift 6.
> Use `let` for static constants, not `var`

- Sources/NIOIMAPCore/Grammar/Command/Command.swift
- Sources/NIOIMAPCore/Grammar/Search/SearchReturnOption.swift
- Tests/NIOIMAPCoreTests/Grammar/ESearch/ESearchOptions+Tests.swift
- Tests/NIOIMAPCoreTests/Grammar/Search/SearchReturnOption+Tests.swift
RFC 7377: Use `RETURN (ALL)` instead of `RETURN ()`
RFC 7377 allows search options `ALL` to be encoded as `RETURN ()` instead of `RETURN (ALL)`, but some servers fail to properly parse this.
We will now encode `[SearchReturnOption.all]` as `RETURN (ALL)` instead of `RETURN ()`.
> RFC 7377: Use `RETURN (ALL)` instead of `RETURN ()`

- EXTENSIONS.md
- Sources/NIOIMAPCore/Grammar/Capability.swift
- Sources/NIOIMAPCore/Grammar/Mailbox/MailboxAttribute.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Mailbox.swift
- Tests/NIOIMAPCoreTests/Grammar/Capability+Tests.swift
- Tests/NIOIMAPCoreTests/Grammar/Mailbox/MailboxAttribute+Tests.swift
- Tests/NIOIMAPCoreTests/Parser/IMAPParserTests.swift
Implement RFC 7889 `APPENDLIMIT`
Support for RFC 7889 “maximum message upload sizes”.
Added both the (normal) `CAPABILITY` part and the mailbox-specific limit through `STATUS` response.
> Implement RFC 7889 `APPENDLIMIT`

- Sources/Proxy/MailClientToProxyHandler.swift
- Sources/Proxy/ProxyToMailServerHandler.swift
- Sources/Proxy/main.swift
This changes the channel handlers for the Proxy to match what the IMAPServerHandler and IMAPClientHandler now expect.
The Proxy command currently is unable to proxy IMAP connections.
This modifies the MailClientToProxyHandler's InboundIn to expect CommandStreamPart rather than SynchronizedCommand, modfiies ProxyToMailServerHandler.channelRead to write a Response rather than a ByteBuffer and modifies Proxy/main to add the ByteToMessageHandler(FrameDecoder()) channel handler before the IMAPServerHandler(), so it gets a FramingResult as input.
Proxy should successfully proxy IMAP connections.
fixes #764
> Fix IMAP Proxy channel pipeline handlers - fixes #764

- Sources/NIOIMAPCore/CommandEncodeBuffer.swift
- Sources/NIOIMAPCore/EncodeBuffer.swift
- Sources/NIOIMAPCore/Grammar/Command/CommandStreamPart.swift
- Sources/NIOIMAPCore/Grammar/ID/ID.swift
- Tests/NIOIMAPCoreTests/Grammar/CommandType/CommandStream+Tests.swift
- Tests/NIOIMAPCoreTests/Grammar/ID/ID+Tests.swift
Add helper for logging CommandStreamPart without PII and special case ID command / response
It is extremely useful to be able to see the key-value pairs of the ID command / response when debugging, but they are currently being redacted (since all strings are by default).
There’s already support for creating a `String` from a `CommandStreamPart` with all PII (personally identifiable information) redacted.
This adds a helper
```swift
extension CommandStreamPart {
public static func descriptionWithoutPII(_ parts: some Sequence<CommandStreamPart>) -> String
}
```
to generate these.
And this adds special logic to _not_ redact the key-value pairs of the [RFC 2971 “ID”](https://datatracker.ietf.org/doc/html/rfc2971) command and response.
`ID` response / command are not being redacted.
> Add helper for logging CommandStreamPart without PII and special case ID command / response

- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser.swift
- Tests/NIOIMAPCoreTests/Parser/IMAPParserTests.swift
Be more lenient about spaces in RFC 2971 ID response
[Archiveopteryx ](https://archiveopteryx.org) inserts extra spaces before the closing `)`.
Skip any additional spaces in the ID response.
> Be more lenient about spaces in RFC 2971 ID response

- Sources/NIOIMAP/Client/FramingParser.swift
- Tests/NIOIMAPTests/FramingParserTests.swift
Allow `DQUOTE` / `"` in lines (frames) of `FramingParser`.
Certain parts (notably `text`) are allowed to have unmatched `"` in them.
Fix `FramingParser`.
Add test case to make sure that
```
S: * OK Hello " foo
S: * NO Hello bar
```
gets framed correctly into 2 “frames” / lines.
Tests pass.
> FramingParser: Allow un-matched DQUOTE in lines

- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierSet.swift
Add a `Sendable` conformance to `MessageIdentificationShiftWrapper`.
Even though this isn't a public type, it's declared to be usable from inline, so its sendability matters externally.
> Declare `MessageIdentificationShiftWrapper` to be `Sendable`

- Sources/CLI/main.swift
- Sources/NIOIMAP/Client/FramingParser.swift
- Sources/Proxy/MailClientToProxyHandler.swift
- Sources/Proxy/main.swift
- Tests/NIOIMAPTests/FramingParserTests.swift
- Tests/NIOIMAPTests/IntegrationTests.swift
FramingParser can crash when single CR is inside DQUOTE string
#776 introduced a bug that could cause a crash (hitting an `assert()`) if the buffer ends with a `CR` (as opposed to `CRLF`) while we’re inside a `"`-string.
We would erroneously always consume the byte after the `CR` or `LF` if we hit a `CR` or `LF` while inside a `"`-string — because we’d call `self.readByte()` twice as a result of calling into `readByte_state_normalTraversal()` from `readByte_state_insideQuoted()`.
Added test case that would crash (due to the `assert()`) prior to this fix.
No crash. 😄
> FramingParser can crash when single CR is inside DQUOTE string

- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Mailbox.swift
- Tests/NIOIMAPCoreTests/Parser/IMAPParserTests.swift
Fix parsing of `NIL` for RFC 7889 `APPENDLIMIT`
#769 implemented RFC 7889, but we fail to parse `APPENDLIMIT NIL` which the server can send if there is no mailbox-specific limit for a particular mailbox, e.g.:
```
C: A1 STATUS INBOX (APPENDLIMIT)
S: * STATUS INBOX (APPENDLIMIT NIL)
S: A1 OK STATUS completed
```
Added test case and fix parsing.
> Fix parsing of NIL for RFC 7889 APPENDLIMIT

- Sources/NIOIMAP/Coders/IMAPServerHandler.swift
- Tests/NIOIMAPTests/Coders/IMAPServerHandlerTests.swift
Fix `IMAPServerHandler` not resetting outstanding continuations.
`IMAPServerHandler` would repeatedly send [Command Continuation Request](https://datatracker.ietf.org/doc/html/rfc3501#section-7.5) because it never reset `numberOfOutstandingContinuationRequests`.
Added unit test.
Reset `numberOfOutstandingContinuationRequests` once the _continuation requests_ have been sent.
> Fix IMAPServerHandler not resetting outstanding continuations

- Sources/NIOIMAP/Coders/ClientStateMachine.swift
Support for [RFC 7888](https://www.rfc-editor.org/rfc/rfc7888) _Non-Synchronizing Literals_ is currently broken in the `IMAPClientHandler` for `APPEND`. This disables those extensions for `APPEND`.
If the connection uses `CommandEncodingOptions` with RFC 7888 _Non-Synchronizing Literals_ the connection will get stuck during `APPEND` because the internal state of the `IMAPClientHandler` is waiting for continuations when there are none.
The normal (non-RFC 7888) flow is
```text
C: A003 APPEND saved-messages (\Seen) {310}
S: + Ready for literal data
C: Date: Mon, 7 Feb 1994 21:52:25 -0800 (PST)
C: ...
```
but with e.g. `LITERAL+` is becomes
```text
C: A003 APPEND saved-messages (\Seen) {310+}
C: Date: Mon, 7 Feb 1994 21:52:25 -0800 (PST)
C: ...
```
but the `IMAPClientHandler` would currently …
> Workaround for IMAPClientHandler and APPEND

- Sources/NIOIMAP/Coders/ClientEncodingOptions.swift
- Sources/NIOIMAP/Coders/ClientStateMachine.swift
- Sources/NIOIMAP/Coders/IMAPClientHandler.swift
- Sources/NIOIMAPCore/CommandEncodingOptions.swift
- Sources/Proxy/MailClientToProxyHandler.swift
- Tests/NIOIMAPTests/Coders/ClientEncodingOptionsTests.swift
- Tests/NIOIMAPTests/Coders/ClientStateMachineTests.swift
- Tests/NIOIMAPTests/Coders/IMAPClientHandlerTests.swift
The encoding options of the `IMAPClientHandler` are not being set properly.
The `IMAPClientHandler` tries to automatically extract incoming server capabilities to update its encoding options. But it fails to pick up capabilities inside a _tagged_ response.
The encoding options furthermore would only be set once an untagged `ID` response was received from the server, and only if the capabilities had previously been received. There should be no such dependency on `ID`.
Finally, code that uses `IMAPClientHandler` should be able to set specific encoding options as it sees fit.
**Note:** This changes the `OutboundIn` type of the `IMAPClientHandler`.
Instead of the current `CommandStreamPart `, it’s now a new `enum`:
```swift
extension IMAPClientHandler {
public enum OutboundIn: Hashable, …
```
> Fix client handler encoding options

- Sources/NIOIMAP/Client/AppendStateMachine.swift
- Tests/NIOIMAPTests/Coders/ClientStateMachineTests.swift
- Tests/NIOIMAPTests/Coders/IMAPClientHandlerTests.swift
Fix receiving untagged responses during `APPEND`
When uploading a message with `APPEND`, the server will send an untagged `* EXISTS` response — and is also allowed to send other so-called _unsolicited data_ as untagged responses. But the `ClientStateMachine` would fail if it received untagged messages while in the _append_ state.
Allow (i.e. ignore) any untagged responses while in the _append_ state.
Also fixed some typos in test names.
Can `APPEND` messages.
> Fix receiving untagged responses during APPEND

- Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierSet.swift
- Tests/NIOIMAPCoreTests/Grammar/MessageIdentifierSet+Tests.swift
Add `MessageIdentifierSet.suffix` overload
This is a fairly common operation when dealing with UIDs, and since `MessageIdentifierSet` is backed by `RangeSet`, we can do this more efficiently than the default implementation.
Adds `MessageIdentifierSet.suffix` and tests.
> Add MessageIdentifierSet.suffix overload

- Sources/NIOIMAP/Coders/IMAPClientHandler.swift
- Sources/NIOIMAP/Coders/ResponseDecoder.swift
- Sources/NIOIMAPCore/Parser/ResponseParser.swift
- Tests/NIOIMAPCoreTests/Parser/ResponseParser+Tests.swift
Pass response parser options into `IMAPClientHandler.init`
When using the `IMAPClientHandler`, there previously was no way to configure the `ResponseParser` it uses. This lead to #763
Add `parserOptions: ResponseParser.Options` to `IMAPClientHandler.init`:
```swift
public init(
encodingOptions: EncodingOptions = .automatic,
parserOptions: ResponseParser.Options = ResponseParser.Options()
)
```
Can now configure the `ResponseParser`. Fixes #763.
> Pass response parser options into IMAPClientHandler.init

- Sources/NIOIMAP/Coders/IMAPClientHandler.swift
- Tests/NIOIMAPTests/Coders/IMAPClientHandlerTests.swift
_[One line description of your change]_
Pick as better name — as discussed in #788
Basically
```diff
- public enum OutboundIn: Hashable, Sendable { … }
+ public typealias OutboundIn = Message
+ public enum Message: Hashable, Sendable { … }
```
> Rename → IMAPClientHandler.Message

- Tests/NIOIMAPCoreTests/Grammar/CommandType/CommandType+Tests.swift
Add additional test case for encoding `\` and `"`
More tests for edge cases.
Added test case.
> Add additional test case for encoding `\` and `"`

- Sources/NIOIMAPCore/Grammar/Mailbox/MailboxName.swift
- Tests/NIOIMAPCoreTests/Grammar/Mailbox/MailboxName+Tests.swift
Improve (pre-calculated) hash of MailboxName
We precalculate `MailboxName`’s `hash` as per #696 — but the quality wasn’t good and caused the `testHashValue()` test to fail on some platforms.
This picks up the 64 bit MurMur3 and uses it to derive a 32 bit value for the hash.
MurMur code is here → https://github.com/aappleby/smhasher/blob/master/src/MurmurHash3.cpp
The implementation isn’t particularly optimized. But the entire point of #696 is that this only gets calculated once.
Better hash value. Tests are no longer failing.
> Improve (pre-calculated) hash of MailboxName

- Sources/NIOIMAPCore/Grammar/Command/Command.swift
- Tests/NIOIMAPCoreTests/Grammar/CommandType/CommandType+Tests.swift
Fix encoding of `UID EXPUNGE`.
Fixes #796
* Correctly encode `UID EXPUNGE`.
* Add some more tests for encoding commands.
> Fix encoding of UID EXPUNGE

- Sources/NIOIMAP/Client/AppendStateMachine.swift
- Sources/NIOIMAP/Client/AuthenticationStateMachine.swift
- Sources/NIOIMAP/Client/IdleStateMachine.swift
- Sources/NIOIMAP/Coders/ClientStateMachine.swift
- Tests/NIOIMAPCoreTests/Grammar/EncodeTestClass.swift
- Tests/NIOIMAPTests/Client/AppendStateMachineTests.swift
- Tests/NIOIMAPTests/Coders/ClientStateMachineTests.swift
Allow receiving untagged responses while running `APPEND` command.
[Section 7.5 “ Server Responses - Command Continuation Request” of RFC 3501](https://www.rfc-editor.org/rfc/rfc3501#section-7.5) show this example of how literals and _ command continuation requests_ work:
```text
C: A001 LOGIN {11}
S: + Ready for additional command text
C: FRED FOOBAR {7}
S: + Ready for additional command text
C: fat man
S: A001 OK LOGIN completed
```
The problem is that when the client sends a command such as
```text
C: A50 SELECT {11}
```
the server may already have enqueued untagged responses. And while the client _has_ to wait for the server’s _ Continuation Request_, it must also allow untagged (and tagged) responses from the server.
For example:
```text
C: A50 SELECT {6}
S: * EXPUNGE 5
S: + Ready …
```
> Allow receiving untagged responses while appending

- EXTENSIONS.md
Looks like a stray character slipped in and broke a Markdown link.
> Fix a typo in EXTENSIONS.md

- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Append.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Body.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Commands.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Date.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Entry.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Envelope.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Fetch.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+List.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Mailbox.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Message.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Partial.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Response.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Search.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Sequence.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+UID.swift
- Sources/NIOIMAPCore/Parser/Grammar/GrammarParser.swift
- Sources/NIOIMAPCore/Parser/UInt8+ParseTypeMembership.swift
Allow crosscompile to linux
Crosscompile is the greatest thing since sliced bread.
As per instructions in: https://www.swift.org/documentation/articles/static-linux-getting-started.html
use:
```
#if os(macOS) || os(iOS)
import Darwin
#elseif canImport(Glibc)
import Glibc
#elseif canImport(Musl)
import Musl
#endif
```
Crosscompilation works!
> Allow crosscompile to linux
